Carlzhu.Iooin V2/Carlzhu.Iooin.Application/Carlzhu.Iooin.WebApp/Areas/CommonModule/Controllers/FormLayoutController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Text;
using System.Web.Mvc;

using Carlzhu.Iooin.Business.CommonModule;

using Carlzhu.Iooin.Entity.CommonModule;
using Carlzhu.Iooin.Framework.Data.DataAccess.DbProvider;
using Carlzhu.Iooin.Framework.Data.WebControl;
using Carlzhu.Iooin.Util;
using Iooin.Framework.Code;


namespace Carlzhu.Iooin.WebApp.Areas.CommonModule.Controllers
{
    /// <summary>
    /// 表单附加属性 控制器
    /// </summary>
    public class FormLayoutController : PublicController<BaseFormAttribute>
    {



        BaseFormAttributeBll Baseformattributebll = new BaseFormAttributeBll();


        public ActionResult FormTest()
        {
            return View();
        }

        public ActionResult FormSubmit()
        {
            BaseDataBaseBll Basedatabasebll = new BaseDataBaseBll();


            StringBuilder sb = new StringBuilder();
            StringBuilder values = new StringBuilder("(");
            DataTable dt = Basedatabasebll.GetColumnList("TestTable");
            List<DbParameter> parameter = new List<DbParameter>();

            sb.Append("INSERT INTO TestTable (");
            foreach (DataRow dr in dt.Rows)
            {
                string filed = dr["column"].ToString();
                parameter.Add(DbFactory.CreateDbParameter($"@{filed}", Request.Form[$"Build_{filed}"]));
                sb.Append($"[{filed}],");
                values.Append($"@{filed},");
            }
            sb.Append(") values");
            values.Append(")");

            base.Repositoryfactory.Repository().ExecuteBySql(sb.Append(values).Replace(",)", ")"), parameter.ToArray());


            Console.WriteLine(parameter);


            return Content("xxxxxxxxxxxxxxxxxxx");
        }



        /// <summary>
        /// 【系统表单】模块目录
        /// </summary>
        /// <returns></returns>
        public ActionResult TreeJson()
        {
            List<BaseModule> list = new BaseModuleBll().GetList();
            List<TreeEntity> TreeList = new List<TreeEntity>();
            foreach (BaseModule item in list)
            {
                string ModuleId = item.ModuleId;
                bool hasChildren = false;
                List<Carlzhu.Iooin.Entity.CommonModule.BaseModule> childnode = list.FindAll(t => t.ParentId == ModuleId);
                if (childnode.Count > 0)
                {
                    hasChildren = true;
                }
                else
                {
                    if (item.Category == "目录")
                    {
                        continue;
                    }
                }
                if (item.Category == "页面")
                    if (item.AllowForm != 1)
                        continue;
                TreeEntity tree = new TreeEntity();
                tree.id = ModuleId;
                tree.text = item.FullName;
                tree.value = ModuleId;
                tree.isexpand = true;
                tree.complete = true;
                tree.hasChildren = hasChildren;
                tree.parentId = item.ParentId;
                tree.img = item.Icon != null ? "/Content/Images/Icon16/" + item.Icon : item.Icon;
                TreeList.Add(tree);
            }
            return Content(TreeList.TreeToJson());
        }


        /// <summary>
        /// 表单设计器
        /// </summary>
        /// <returns></returns>
        [ManagerPermission(PermissionMode.Enforce)]
        public ActionResult Layout()
        {
            string ModuleId = Request["ModuleId"];
            string strhtml = Baseformattributebll.CreateBuildFormTable(2, ModuleId);
            ViewBag.BuildFormTable = strhtml;
            return View();
        }
    }
}

Carlzhu.Iooin V2/Carlzhu.Iooin.Application/Carlzhu.Iooin.WebApp/Areas/eForm/Controllers/FController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Carlzhu.Iooin.Business;
using Carlzhu.Iooin.Business.FormModule;
using Carlzhu.Iooin.Business.TpaModule;


using Carlzhu.Iooin.Entity;
using Carlzhu.Iooin.Entity.BaseUtility;
using Carlzhu.Iooin.Entity.CommonModule;
using Carlzhu.Iooin.Entity.FORM;
using Carlzhu.Iooin.Entity.FORM.f;
using Carlzhu.Iooin.Entity.FORM.f.draw;
using Carlzhu.Iooin.Framework.Data.DataAccess;
using Carlzhu.Iooin.Framework.Data.Repository;
using Carlzhu.Iooin.Util;
using WebGrease.Css.Extensions;

namespace Carlzhu.Iooin.WebApp.Areas.eForm.Controllers
{
    public class FController : FormControllerBase
    {

        //
        // GET: /F/

        private string FormNo { get; set; }
        private List<BaseEmployee> _employees;

        #region 申请表单

        /// <summary>
        /// 生成表单页面,主要作用是生成备注页
        /// </summary>S
        /// <param name="formId"></param>
        /// <param name="formNo"></param>
        /// <param name="method"></param>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult FormComm(int formId = 0, string formNo = "", string method = "Add")
        {

            //ViewData["Method"] = method;

            F model = new FormTest();

            if (formId > 0)
            {
                model.Form = new Form { FormType = new BaseServices<FormType>().LoadEntities(c => c.FormId == formId).First() };
                model.Form.FormType.FormId = formId;
            }
            else
            {
                if (!string.IsNullOrEmpty(formNo))
                {
                    var formType = new Applying().GetFormByFormNo(formNo).FormType;
                    var formbody = new Applying().GetFormEntityByFormNo(formNo);
                    model = formType.IsModel ? formbody : ((IEnumerable<F>)formbody).First();
                }
            }


            return PartialView($"~/Areas/eForm/Views/FormComm/FormComm{method}.cshtml", model);
        }





        /// <summary>
        /// 表单申请页面
        /// </summary>
        /// <param name="formId"></param>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult ApplyForm(int formId)
        {
            var formType = new BaseServices<FormType>().LoadEntities(c => c.FormId == formId).First();

            ViewBag.DropCustomer = Task.Run(() => new TpaCustomerBll().GetCustomerDropList(null)).Result;
            ViewBag.DropSupplier = Task.Run(() => new TpaSupplierBll().GetSupplierDropList()).Result;
            ViewBag.FormType = formType;

            //随便初始化一个F对像
            F<FormDrawingsBom> f = new F<FormDrawingsBom>();
            var type = f.ReflectionByFormType(formType);

            ////var newfile = System.IO.File.ReadAllText(Server.MapPath($"~/Areas/eForm/Views/{formType.FormPage.Substring(4)}.cshtml"));
            ////创建一个临时cshtml文件
            //string file = $"~/Areas/eForm/Views/formtemp/{formType.FormName}B.cshtml";
            //if (!System.IO.File.Exists(file))
            //{
            //    System.IO.File.WriteAllText(Server.MapPath(file), formType.EditHtml, Encoding.UTF8);
            //}
            //return PartialView(file, formType.IsModel ? Activator.CreateInstance(type) : Activator.CreateInstance(typeof(List<>).MakeGenericType(type)));

            return View($"~/Areas/eForm/Views/{formType.FormPage.Substring(4)}.cshtml",
                         formType.IsModel
                             ? Activator.CreateInstance(type)
                             : Activator.CreateInstance(typeof(List<>).MakeGenericType(type)));

        }


        public ActionResult InitEditBody()
        {
            string s = string.Empty;

            foreach (var formType in new BaseServices<FormType>().LoadEntities(c => true).ToList())
            {

                try
                {
                    formType.EditHtml = System.IO.File.ReadAllText(Server.MapPath($"~/Areas/eForm/Views/{formType.FormPage.Substring(4)}.cshtml"));
                    formType.DetailsHtml = System.IO.File.ReadAllText(Server.MapPath($"~/Areas/eForm/Views/{formType.FormPage.Substring(5)}Details.cshtml"));

                    if (new BaseServices<FormType>().UpdateEntity(formType))
                    {
                        s += formType.FormId + ",";
                    }

                }
                catch (Exception)
                {
                    continue;
                }


            }



            return Content(s);
        }





        /// <summary>
        /// 生成表单实体
        /// </summary>
        /// <param name="dictionary"></param>
        /// <param name="employees">返回签核人信息至前台</param>
        /// <returns></returns>
        [NonAction]
        private Form CreateForm(Dictionary<string, object> dictionary, out List<BaseEmployee> employees)
        {

            int formId = int.Parse(dictionary["formid"].ToString());
            employees = new Applying().GetSignListByFormId(dictionary, formId, EmpNo);

            var form = new Form
            {
                FormNo = new Applying().CreateFormNo(new object()),
                FormId = formId,
                CreateEmpNo = EmpNo,
                CreateTime = DateTime.Now,
                SignPath = string.Join(",", employees.Select(c => c.EmpNo)) + ",",
                FormStatus = (int)Form.StatusEnum.未送出,
                IsEmergents = dictionary.ContainsKey("isemergents")
                //Explain = dictionary["Form.Explain"].ToString()

            };
            FormNo = form.FormNo;
            return form;
        }

        #endregion

        #region 修改表单


        /// <summary>
        /// 主要用来修改表单时查找表单备注
        /// </summary>
        /// <param name="formNo"></param>
        /// <returns></returns>
        public string GetFormMark(string formNo)
        {
            return ((F)(new Applying().GetFormEntityByFormNo(formNo))).Mark;
        }



        /// <summary>
        /// 表单修改页
        /// </summary>
        /// <param name="formNo"></param>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult EditForm(string formNo)
        {
            //取得表单序号，查看表单存放的实体类
            var formType = new Applying().GetFormByFormNo(formNo).FormType;


            ViewBag.DropCustomer = Task.Run(() => new TpaCustomerBll().GetCustomerDropList(null)).Result;
            ViewBag.DropSupplier = Task.Run(() => new TpaSupplierBll().GetSupplierDropList()).Result;
            ViewBag.FormType = formType;



            ////创建一个临时cshtml文件
            //string file = $"~/Areas/eForm/Views/formtemp/{formType.FormName}A.cshtml";
            //if (!System.IO.File.Exists(file))
            //{
            //    System.IO.File.WriteAllText(Server.MapPath(file), formType.EditHtml, Encoding.UTF8);
            //}


            //return PartialView(file,new Applying().GetFormEntityByFormNo(formNo, formType));


            return PartialView($"~/Areas/eForm/Views/{formType.FormPage.Substring(4)}.cshtml",
                new Applying().GetFormEntityByFormNo(formNo, formType));

        }









        /// <summary>
        /// 修改表单
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditForm()
        {
            Dictionary<string, object> dictionary = Request.Form.Cast<object>().ToDictionary<object, string, object>(para => para.ToString(), para => Request.Form[para.ToString()]);

            FormType formType = new BaseServices<FormType>().LoadEntities(c => c.FormId == int.Parse(Request.Params["formid"])).FirstOrDefault();
            if (formType != null)
            {
                return GetRequetMethod(dictionary, formType, formType.IsModel ? "Edit" : "ListEdit");
            }

            return Link.ErrorBy(new Exception("系统参数错误，请返回重试"), GetType());
        }

        /// <summary>
        /// 提交修改结果
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="dictionary"></param>
        /// <returns></returns>
        [NonAction]
        private ActionResult Edit<T>(Dictionary<string, object> dictionary) where T : F, new()
        {
            return new F<T>().EditForm(ReflectionModelByForm<T>(dictionary, ""), dictionary["FormNo"].ToString()) ? EditSuccess() : EditError();
        }

        [NonAction]
        private ActionResult ListEdit<T>(Dictionary<string, object> dictionary) where T : F, new()
        {
            var listEntity = new List<T>();
            for (int i = 1; i <= 10; i++)
            {
                if (!dictionary.ContainsKey("IsValid" + i)) continue;
                listEntity.Add(ReflectionModelByForm<T>(dictionary, i.ToString(CultureInfo.InvariantCulture))); ;
            }
            return new F<T>().EditForm(listEntity, dictionary["FormNo"].ToString()) ? EditSuccess() : EditError();
        }

        [NonAction]
        private ActionResult EditSuccess()
        {
            var conso = WebHelper.GetCookie("url");

            if (!string.IsNullOrEmpty(conso))
            {
                return Redirect(conso);
            }
            return RedirectToAction("Applyed", "Tracking");

        }

        [NonAction]
        private static ActionResult EditError()
        {
            return Link.ErrorBy(new Exception("修改失败，请返回重试"), typeof(FController));
        }

        #endregion

        #region 保存表单

        /// <summary>
        /// 提交表单
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SubmitForm()
        {

Carlzhu.Iooin V2/Carlzhu.Iooin.Application/Carlzhu.Iooin.WebApp/Controllers/DownloadController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Carlzhu.Iooin.Business.BaseModule;

using Carlzhu.Iooin.Entity;
using Carlzhu.Iooin.InteractiveAdapter;
using Carlzhu.Iooin.Util;
using Carlzhu.Iooin.Util.Offices;
using Files = Carlzhu.Iooin.Entity.FORM.Files;

//using FilesFileGroup = Base.FilesFileGroup;

namespace Carlzhu.Iooin.WebApp.Controllers
{
    public class DownloadController : Controller
    {
        //
        // GET: /Download/


        private readonly DownDetailsBll _details = new DownDetailsBll();


        public void Chrome()
        {
            var down = new DownLoad();
            down.DownloadFunc += _details.Chrome;
            down.Down(new DownloadEventArgs());
        }

        public void PublishedTemplate()
        {
            var down = new DownLoad();
            down.DownloadFunc += _details.PublishedTemplate;
            down.Down(new DownloadEventArgs());
        }


        /// <summary>
        /// 加密文件下载
        /// </summary>
        /// <param name="md5"></param>
        public void Form(string md5)
        {
            var down = new DownLoad();
            down.DownloadFunc += _details.Form;
            down.Down(new DownloadEventArgs { Md5 = md5.Decrypt() });
        }


        public JsonResult GetGroupFiles(string groupGuid)
        {

            List<Files> fs = new List<Files>();

            new Carlzhu.Iooin.Business.BaseModule.FilesFileGroupBll().GetFileListByGroupGuid(Guid.Parse(groupGuid)).ForEach(c => fs.Add(new Files { FileName = c.Files.FileName, Md5 = c.Files.Md5 }));


            var serializer = new JavaScriptSerializer();

            return Json(serializer.Serialize(fs));

        }




        public void Online(string md5, string method)
        {

            string d5 = md5.Decrypt();

            var file = new FilesBll().SignFiles(d5);

            string uppath = BaseHelper.UpPath;





            if (".pdf".Contains(file.FileType))
            {
                //打印与在线查看
                BaseHelper.ViewPdf(method == "print"
                    ? PdfHelper.PdfToStream(uppath + d5, true, null, "mjdrawadm", true, "表单文件",
                        "minicutdraw.png")
                    : PdfHelper.PdfToStream(uppath + d5, true, null, "mjdrawadm", false, "表单文件",
                        "minicutdraw.png"));

            }
            else
            {
                Form(md5);
                //   Link.ErrorBy(new Exception(string.Format("暂不支持{0}文件在线查看，请等待开发...", file.FileType)));
            }


        }


    }
}

Carlzhu.Iooin V2/Carlzhu.Iooin.Application/Carlzhu.Iooin.WebApp/Areas/eForm/Views/f/formLayout/_DrawingBase.cshtml
@using Carlzhu.Iooin.Entity.FORM
@using Carlzhu.Iooin.Framework.Data.Repository
@model Carlzhu.Iooin.Entity.FORM.f.draw.DrawingsBase


<tr>
    <th>@Html.LabelFor(model => model.Customer.CustomerName)</th>
    <td>@(new Carlzhu.Iooin.Business.TpaModule.TpaCustomerBll().GetCustomerNameByNo(Model.CustomerNo))</td>

    <th>@Html.LabelFor(model => model.PageSize)</th>
    <td>@Html.DisplayTextFor(model => model.PageSize)</td>
</tr>
<tr>
    <th>@Html.LabelFor(model => model.DrawVer)</th>
    <td>@Html.DisplayTextFor(model => model.DrawVer)</td>

    <th>@Html.LabelFor(model => model.Reason)</th>
    <td>@Html.DisplayTextFor(model => model.Reason)</td>

</tr>
<tr>
    <th>@Html.LabelFor(model => model.FileGroup)</th>
    <td colspan="3">
        @foreach (var file in new Carlzhu.Iooin.Business.BaseModule.FilesFileGroupBll().GetFileListByGroupGuid(Model.FileGroup))
        {
            var ff = DataFactory.Database().FindEntity<Files>(file.Md5);

            @Html.Partial("~/Areas/eForm/Views/F/formLayout/_FileDetails.cshtml", ff);
        }
    </td>
</tr>

<tr><td colspan="4"><hr /></td></tr>
@RenderBody()

Carlzhu.Iooin V2/Carlzhu.Iooin.Application/Carlzhu.Iooin.WebApp/Areas/eForm/Views/f/formLayout/_DrawingBaseEdit.cshtml
@using Carlzhu.Iooin.Business.TpaModule
@model Carlzhu.Iooin.Entity.FORM.f.draw.DrawingsBase


<tr>
    <th>@Html.LabelFor(model => model.Customer.CustomerName)</th>
    <td>@Html.DropDownList("CustomerNo", new TpaCustomerBll().GetCustomerDropList(""), new { CLASS = "form-contorl" })</td>
    <td>@Html.ValidationMessageFor(model => model.CustomerNo)</td>
    <th>@Html.LabelFor(model => model.PageSize)</th>
    <td>@Html.TextBoxFor(model => model.PageSize)</td>
    <td>@Html.ValidationMessageFor(model => model.PageSize)</td>
</tr>
<tr>
    <th>@Html.LabelFor(model => model.DrawVer)</th>
    <td>@Html.EditorFor(model => model.DrawVer)</td>
    <td>@Html.ValidationMessageFor(model => model.DrawVer)</td>
    <th>@Html.LabelFor(model => model.Reason)</th>
    <td>
        @Html.DropDownList("Reason", new List<SelectListItem>()
                    {
                        new SelectListItem {Text = "新发行",Value = "新发行",Selected = Model.Reason=="新发行"},
                        new SelectListItem {Text = "ECN变更",Value = "ECN变更",Selected =Model.Reason=="ECN变更"},
                    })
    </td>
    <td>@Html.ValidationMessageFor(model => model.Reason)</td>
</tr>
<tr>
    <th>@Html.LabelFor(model => model.FileGroup)</th>
    <td>@Html.TextBoxFor(model => model.FileGroup, new { READONLY = "READONLY", placeholder = "点击上传文件", title = "点击上传文件" })</td>
    <td>@Html.ValidationMessageFor(model => model.FileGroup)</td>
    <td colspan="2" id="upFileList"></td>
    <td></td>
</tr>
<tr><td colspan="6"><hr /></td></tr>
@RenderBody()




<script type="text/javascript">
    $("input:not([type='checkbox']),select").removeClass("form-control input-sm");
</script>

Carlzhu.Iooin V2/Carlzhu.Iooin.Application/Carlzhu.Iooin.WebApp/Areas/eForm/Views/f/formLayout/_FileDetails.cshtml
@using Carlzhu.Iooin.InteractiveAdapter
@model Carlzhu.Iooin.Entity.FORM.Files

@{
    string md = (Model.Md5.Encrypt());
    <div class="btn-group">
        <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown" title="@(Model.FileName)">
            @Model.FileName.ToCut(18) <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">

            @if (Model.FileType == ".pdf")
            {
                <li>@Html.ActionLink("查看...", "Online", "Download", new { md5 = md, method = "view", area = "" }, new { TARGET = "_blank" })</li>
                <li class="divider"></li>
                <li>@Html.ActionLink("打印...", "Online", "Download", new {md5 = md, method = "print", area = ""}, new {TARGET = "_blank"})</li>
                <li class="divider"></li>
            }

            <li>@Html.ActionLink("下载...", "Form", "Download", new { md5 = md, area = "" }, new { TARGET = "_blank" })</li>

        </ul>
    </div>
}